name: licensing

services:
  document_db:
    image: ${DOCUMENTDB_IMAGE:-ghcr.io/documentdb/documentdb/documentdb-local:latest}
    environment:
      - USERNAME=${DOCUMENTDB_USER:-docdb}
      - PASSWORD=${DOCUMENTDB_PASSWORD:-password}
    ports:
      - ${DOCUMENTDB_PORT:-10260}:10260
